import Head from 'next/head'
import React from 'react'
import Footer from '../components/Footer'
import Navbar from '../components/Navbar'
import Link from 'next/dist/client/link'
import Button from '../components/Button'
import { useState } from 'react'
function singlelist() {
    const [slideNumber, setSlidNumber] = useState(0)
    const [open, setOpen] = useState(false)
    const listPhotos = [
        {
            src: "https://a0.muscache.com/im/pictures/4d268e76-949f-4de7-a10b-b4b48ea3355d.jpg?im_w=1200"
        },
        {
            src: "https://a0.muscache.com/im/pictures/4f4e82b1-3270-4c5a-9628-83ab64ae8f58.jpg?im_w=1440"
        },
        {
            src: "https://a0.muscache.com/im/pictures/ca4e39b3-ab0f-4a0e-b10f-7297bd4db5da.jpg?im_w=1440"
        },
        {
            src: "https://a0.muscache.com/im/pictures/75607a14-a5ce-474a-a316-15ecaed1fbe9.jpg?im_w=1440"
        },
        {
            src: "https://a0.muscache.com/im/pictures/732cce19-b748-4a47-b468-91e26c8aebab.jpg?im_w=1440"
        },
        {
            src: "https://a0.muscache.com/im/pictures/58a06ecf-f3c0-45b1-a1a6-3a091cf4abe2.jpg?im_w=1440"
        },
        {
            src: "https://a0.muscache.com/im/pictures/5b621336-d65a-4283-8072-dbc414626894.jpg?im_w=1440"
        },
        {
            src: "https://a0.muscache.com/im/pictures/9a6f355e-7a3e-4273-ab6f-34e1335fb073.jpg?im_w=1440"
        },

    ]
    const handleOpen = (i) => {
        setSlidNumber(i)
        setOpen(true)
    }

    const handleMove = (direction) => {
        let newSlideNumber; 

        if(direction === 'l') {
            newSlideNumber = slideNumber === 0 ? 8 : slideNumber - 1
        }
        else {
            newSlideNumber = slideNumber === 8 ? 0 : slideNumber + 1
        }

        setSlidNumber(newSlideNumber)
    }
  return (
    <div>
    <Head>
        <title>Nature Observatory on Secluded Island</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
        <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Ubuntu:ital,wght@0,300;0,400;0,500;0,700;1,300&display=swap" rel="stylesheet"></link>
      </Head>
         <Navbar />
            <div className='relative'>
            { open && <div className='slider'>
               <div className='sliderWrapper relative'>
                    <div className='iconBack'>
                        <ion-icon onClick={() => handleMove('l')}  name="arrow-back-circle-outline"></ion-icon>
                    </div>
                   <img src={listPhotos[slideNumber].src} className='sliderImage' alt='photo' />
                   <div className='iconClose'>
                     <ion-icon onClick={()=> setOpen(false)} name="close-outline"></ion-icon>
                    </div>
                   <div className='iconNext'>
                    <ion-icon onClick={() => handleMove('r')} name="arrow-forward-circle-outline"></ion-icon>
                    </div>
               </div>
                </div>}
            <div className='singContainer mt-[200px] md:mt-[150px]'>
                 <div className='singleWrapper'>
                  <div className='mb-5'>
                       <div className='mt-10'>
                           <h1 className='font-bold text-[25px] md:text-[45px]  text-gray-800 font-[Ubuntu]'>Canon Camera EOS 90D</h1>
                           <div className='mt-5 flex flex-col md-flex-row justify-between'>
                                <div className='singleAddress text-lg font-[Ubuntu] flex items-center'>
                                    <ion-icon name="navigate-outline"></ion-icon>
                                    <span className='ml-2'> Izmir Konak 12/46 sk bina 16</span>
                                </div>
                                <div className='sharebnt flex gap-8'>
                                <div className='text-[19px] flex items-center justify-center gap-2 cursor-pointer underline font-semibold'>
                                    <ion-icon name="share-outline"></ion-icon>
                                    Share
                                </div>
                                <div className='text-[19px] flex items-center justify-center gap-2 cursor-pointer underline font-semibold'>
                                    <ion-icon name="heart-outline"></ion-icon>
                                    Save
                                </div>
                                </div>
                           </div>
                       </div>
                  </div>
                     <div className='listingImages grid  grid-cols-1 md:grid-cols-4 gap-2'>
                        {
                            listPhotos.map((photo, i) => (
                                <div className='singleListImgWrapper cursor-pointer'>
                                    <img onClick={() => handleOpen(i)} src={photo.src} />
                                </div>
                            ))
                        }
                     </div>
                     <div className='singDetails mt-10'>
                        <div className='detailsText p-8 shadow-2xl rounded-2xl'>
                            <div className='p-5 border-2 rounded-3xl'>
                            <h2 className=' font-bold text-[21px] md:text-[45px]  text-gray-800 font-[Ubuntu]'>Nature Observatory on Secluded Island</h2>
                            <p className='details-desc'>
                                Quant self-catering cabin gently nestled into the historic family-run Dry Island. "Otter Cabin" is fitted out to a high standard with a double bedroom, shower room, open plan kitchen and living room and its own hot tub and decking area. This is a traditional self-catering unit. Kitchen basics and linens are provided. High-speed wifi is available. Unfortunately, the cabin is inaccessible to those with mobility difficulties.
                            </p>
                            </div>
                            <div>
                                <iframe class="w-full rounded-3xl mt-4" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d85064.4693514394!2d16.310020473793294!3d48.22077800486599!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x476d079e5136ca9f%3A0xfdc2e58a51a25b46!2sViyana%2C%20Avusturya!5e0!3m2!1str!2str!4v1657887162476!5m2!1str!2str" width="600" height="450"  allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
                            </div>
                        </div>
                        <div className='p-8 rounded-2xl shadow-2xl text-center'>
                            <img className="h-32 w-32 object-cover rounded-full m-auto border-yellow-600 border-2" src='https://cindria-demo.netlify.app/assets/img/dd.jpg'/>
                            <h2 className='font-bold mt-2 text-2xl'>
                                Vahid Bro
                            </h2>
                            <span className='block'>	&#9733; 1058</span>
                            <span className='mb-5 inline-block mt-4'>
                               I am Vahid Bro, Top Seller in Rentulo 
                            </span>
                            <div className='flex gap-5 flex-col'>
                                <button className='bg-[#49C858] text-white py-2 rounded-xl'>
                                <ion-icon name="logo-whatsapp"></ion-icon> WHATSAPP
                                </button>
                                <button className='bg-[#EFA83C] text-white py-2 rounded-xl'>
                                <ion-icon name="call-outline"></ion-icon> DIRECT CALL
                                </button>
                                <button className='bg-yellow-600 text-white py-2 rounded-xl'>
                                <ion-icon name="mail-outline"></ion-icon> MESSAGE
                                </button>
                
                            </div>
                        </div>
                     </div>
                 </div>
             </div> 
            </div>
         <Footer/>
    </div>
  )
}

export default singlelist