import Head from 'next/head'
import Banner from '../components/Banner'
import Categories from '../components/Categories';
import FeaturedProperties from '../components/FeaturedProperties';
import Footer from '../components/Footer';
import Header from '../components/Header'
import LargCard from '../components/LargCard';
import MailList from '../components/MailList';
import MediumCard from '../components/MediumCard';
import LatestProperties from '../components/LatestProperties';
import SmallCard from '../components/SmallCard';
import RealState from '../components/RealState';
import Link from 'next/link';
import Navbar from '../components/Navbar';

export default function Home({ exploreData, featuredProducts,  img, title, decs, buttonText  }) {
  return (
    <div>
      <Head>
        <title>Rentuli</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
        <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
      </Head>
     <Navbar />
     <LargCard 
     img='https://links.papareact.com/4cj'
     title="Welcome to Rentulo"
     decs="Best place to buy and sell"
     buttonText="Get Stared Now"/>
     <div className='homeContainer md:max-w-[75%] mx-auto'>
     <h2 className='text-[27px] font-bold'>Categories</h2>
    
        <Categories/>

         <h2 className='text-[27px] font-bold'>Latest Entries</h2>
         <LatestProperties />

         <h2 className='text-[27px] font-bold'>Featured Properties</h2>
          <FeaturedProperties />
          <h2 className='text-[27px] font-bold'>Top Real-State Entries</h2>
        <RealState />
     </div>

     <MailList />
      <Footer />
    </div>
  )
}

// export async function getStaticProps(){
//   const exploreData = await fetch('https://links.papareact.com/pyp')
//   .then(
//    (res) => res.json()
//   );
  
//   const featuredProducts = await fetch('https://links.papareact.com/zp1')
//   .then(
//     (res) => 
//     res.json()
//   );

//   return {
//     props: {
//       exploreData: exploreData,
//       featuredProducts: featuredProducts
//     }
//   }

// }

