import Head from 'next/head'
import Link from 'next/link'
import React from 'react'
import Button from '../components/Button'
import Footer from '../components/Footer'
import Navbar from '../components/Navbar'

export default function login() {
  return (
    <div className='bg-gray-100'>
        <Head>
        <title>Register to Rentulo</title>
        <meta name="description" content="Generated by create next app" />
        <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
        <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
      </Head>
        <Navbar />
        <mail class="flex flex-col items-center justify-center w-full flex-1 px-20 text-center pt-[200px] mb-10">
          <div className='bg-white rounded-2xl shadow-2xl flex flex-col md:flex-row  md:max-w-4xl w-[100%]'>
              <div className='md:w-3/5 p-5'>
                 <div className='text-left font-bold text-2xl'>
                    <span className='text-yellow-500'>Rent</span>ulo
                 </div>
                 <div className='py-10'>
                    <h2 className='text-yellow-500 text-2xl font-bold mb-2'>Sign In to Rentulo</h2>
                    <div className='border-2 w-10 border-yellow-500 inline-block mb-2'></div>
                    <div className='flex gap-3 justify-center my-2'>
                       <a href=''  className="text-yellow-600 border-yellow-600 border rounded-full flex item-center p-1"><ion-icon name="logo-facebook"></ion-icon></a>
                       <a href=''className="text-yellow-600 border-yellow-600 border rounded-full flex item-center p-1" ><ion-icon name="logo-google"></ion-icon></a>
                       <a href='' className="text-yellow-600 border-yellow-600 border rounded-full flex item-center p-1" ><ion-icon name="logo-linkedin"></ion-icon></a>
                    </div>
                    <p className='text-gray-400 text-xs m2-5 mb-5 inline-block'>Or use your email address.</p>
                    <div className='flex flex-col items-center'>
                       <div className='bg-gray-100 w-[90%] p-2 text-left mb-3 flex items-center gap-1 rounded-2xl'>
                           <ion-icon name="mail-outline"></ion-icon>
                           <input type="email" name="email" required className='bg-transparent outline-none' placeholder='Email Address' />
                       </div>
                       <div className='bg-gray-100 w-[90%] p-2 text-left mb-3 flex items-center gap-1 rounded-2xl'>
                           <ion-icon name="lock-closed-outline"></ion-icon>
                           <input type="password" name="password" required className='bg-transparent outline-none w-[100%] ' placeholder='Passowrd' />
                       </div>
                       <div className='flex w-[90%] justify-between'>
                           <label className='flex gap-2 items-center text-xs text-gray-600'>
                                <input type="checkbox" name="remember"/> Remember Me
                           </label>
                           <a href='#' className='text-xs text-gray-600 underline'>Forgot Passwor</a>
                       </div>
                       <a href='#' className='border-2 bg-yellow-600 text-white rounded-full inline-block mt-2 py-2 px-10 hover:bg-gray-700 transition-all ease-out hover:border-white w-[250px]'>Login</a>
                    </div>
                 </div>
              </div>

             <div className='md:w-2/5  bg-yellow-500 text-white md:rounded-r-2xl py-10 md:py-36 px-12 '>
                <h2 className='text-3xl font-bold mb-2'>Hello, There</h2>
                <div className='border-2 w-10 inline-block mb-2'></div>
                <p className='mb-2'>Start your Journy with Rentulo</p>
                <Link href={'./register'}>
                    <p className='border-2 border-white rounded-full inline-block mt-2 py-2 px-10 hover:bg-gray-700 transition-all ease-out hover:border-gray-700 cursor-pointer'>Sign Up</p>
                </Link>
             </div>
          </div>
        </mail>
        <Footer/>
    </div>
  )
}
